name: CI
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno install --frozen
      - name: Test
        run: deno task test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno install --frozen
      - run: deno task check-type
      - run: deno task check-fmt
      - run: deno publish --dry-run
        if: ${{github.ref_name == 'main'}}
